from . import config_word_slip
from . import word_slip
from . import form_word_slip
from . import register_shift
from . import register_shift_rel
from . import config_shift
from . import register_work
from . import register_overtime
from . import employee_attendance
from . import synthetic_work
from . import config_reason
