from . import mdm_chung_loai1
from . import mdm_chung_loai2
from . import mdm_linh_vuc
from . import mdm_nganh_hang
from . import mdm_nhan_hang
from . import mdm_chat_lieu
from . import mdm_do_bong
from . import mdm_do_day
from . import mdm_dung_tich
from . import mdm_hh_type
from . import mdm_tong_hop
from . import ket_qua_tong_hop
from . import mdm_quoc_gia
from . import mdm_chi_nhanh
from . import mdm_nhom_khach
from . import mdm_saleman
from . import mdm_tinh
from . import mdm_khu_vuc
from . import mdm_quan_ly_vung
from . import mdm_khach_hang
from . import ket_qua_khach_hang
from . import buoc_duyet_hang_hoa
from . import buoc_duyet_khach_hang
from . import phuong_xa_cu
from . import quan_huyen_cu
from . import plan
from . import tinh_cu
from . import mien_lon
from . import mien_nho
