from . import master_data_report
from . import employee_attendance_report
from . import synthetic_work_report
from . import employee_shift_report
from . import leave_report
from . import synthetic_leave_report
from . import sonha_employee_report
from . import sonha_contract_report
from . import config_template_report
from . import reward_report
from . import discipline_report
from . import dismissal_report
