{
    'name': 'Master Data SonHa',
    'version': '1.0',
    'summary': 'Master Data SonHa',
    'category': 'Uncategorized',
    'license': 'LGPL-3',
    'depends': [
        'hr',
        'base',
        'uom'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/md_customer_views.xml',
        'views/md_product_views.xml',
        'views/purchasing_group_views.xml',
        'views/item_category_group_views.xml',
        'views/uom_characteristic_views.xml',
        'views/mrp_controller_views.xml',
        'views/special_procument_type_views.xml',
        'views/profit_center_views.xml',
        'views/x_material_type_views.xml',
        'views/x_mch_list_views.xml',
        'views/x_division_views.xml',
        'views/x_product_hierarchy_views.xml',
        'views/sale_organization_views.xml',
        'views/distribution_channel_views.xml',
        'views/tax_classification_views.xml',
        'views/account_assignment_views.xml',
        'views/material_price_group_views.xml',
        'views/valuation_class_views.xml',
        'views/overhead_group_views.xml',
        'views/md_supplier_views.xml',
        'views/md_stock_views.xml',
        'views/product_line_views.xml',
        'views/product_stage_views.xml',
        'views/product_brand_views.xml',
        'views/product_color_views.xml',
        'views/product_capacity_views.xml',
        'views/product_chemical_views.xml',
        'views/product_model_views.xml',
        'views/product_style_views.xml',
        'views/product_substance_views.xml',
        'views/product_name_rule_views.xml',
        'views/product_diameter_views.xml',
        'views/product_size_views.xml',
        'views/product_surface_views.xml',
        'views/product_thickness_views.xml',
        'views/product_other_views.xml',

        'views/md_approve_rule_views.xml',
        'views/md_approve_role_views.xml',
        'views/config_district_views.xml',
        'views/config_ward_views.xml',
        'views/declare_md_customer_views.xml',
        'views/declare_md_supplier_views.xml',
        'views/declare_md_product_views.xml',

        'views/bank_country_views.xml',
        'views/bank_data_views.xml',
        'views/trading_partner_views.xml',
        'views/reconciliation_account_views.xml',
        'views/payment_term_views.xml',
        'views/cus_payment_method_views.xml',
        'views/sale_district_views.xml',
        'views/cus_incoterm_views.xml',
        'views/cus_group_views.xml',
        'views/cus_group_1_views.xml',
        'views/customer_price_group_views.xml',
        'views/shipping_condition_views.xml',
        'views/customer_assignment_group_views.xml',
        'views/sale_office_views.xml',
        'views/vendor_industry_views.xml',
        'views/form_organization_views.xml',
        'views/planning_group_views.xml',
        'views/order_currency_views.xml',
        'views/bp_type_views.xml',
        'views/bp_group_account_views.xml',
        'views/declare_md_saleman_views.xml',
        'views/company_code_views.xml',
        'views/md_saleman_views.xml',
        'views/limit_area_views.xml',
        'views/sonha_plant_views.xml',
        'wizard/wizard_md_material_views.xml',
        'wizard/wizard_import_infor_views.xml',
        'wizard/wizard_assign_staff_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sonha_master_data/static/src/style.css',
        ],
    },
    'auto_install': False,
    'application': True,
    'installable': True,
}