{
    'name': 'Master Data SonHa',
    'version': '1.0',
    'summary': 'Master Data SonHa',
    'category': 'Uncategorized',
    'license': 'LGPL-3',
    'depends': [
        'hr',
        'base',
        'stock',
        'uom'
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/md_customer_views.xml',
        'views/customer_type_views.xml',
        'views/customer_group_views.xml',
        'views/md_product_views.xml',
        'views/purchasing_group_views.xml',
        'views/item_category_group_views.xml',
        'views/uom_characteristic_views.xml',
        'views/mrp_controller_views.xml',
        'views/special_procument_type_views.xml',
        'views/profit_center_views.xml',
        'views/x_material_type_views.xml',
        'views/x_mch_list_views.xml',
        'views/x_division_views.xml',
        'views/x_product_hierarchy_views.xml',
        'views/stock_warehouse_views.xml',
        'views/sale_organization_views.xml',
        'views/distribution_channel_views.xml',
        'views/tax_classification_views.xml',
        'views/account_assignment_views.xml',
        'views/material_price_group_views.xml',
        'views/valuation_class_views.xml',
        'views/overhead_group_views.xml',
        'views/md_supplier_views.xml',
        'views/supplier_type_views.xml',
        'views/supplier_group_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sonha_master_data/static/src/style.css',
        ],
    },
    'auto_install': False,
    'application': True,
    'installable': True,
}