from odoo import models, fields


class ExcelLangSon(models.Model):
    _name = 'excel.data.lang.son'

    soHopDong = fields.Char(string='Số Hợp Đồng')
    maDongHo = fields.Char(string='Mã Đồng Hồ')
    seriDongHo = fields.Char(string='Sê-ri Đồng Hồ')
    maKhachHang = fields.Char(string='Mã Khách Hàng')
    tenKhachHang = fields.Char(string='Tên Khách Hàng')
    diaChi = fields.Char(string='Địa Chỉ')
    thuTuGhi = fields.Char(string='Thứ Tự Ghi')
    maKyGhiChiSo = fields.Char(string='Mã Kỳ Ghi Chỉ Số')
    nam = fields.Char(string='Năm')
    thang = fields.Char(string='Tháng')
    canBoDoc = fields.Char(string='Cán Bộ Đọc')
    maTuyenDoc = fields.Char(string='Mã Tuyến Đọc')
    maPhamVi = fields.Char(string='Mã Phạm Vi')
    chiSoDau = fields.Char(string='Chỉ Số Đầu')
    chiSoCuoi = fields.Char(string='Chỉ Số Cuối')
    ngayDoc = fields.Char(string='Ngày Đọc')
    trangThaiSoDoc = fields.Char(string='Trạng Thái Sổ Đọc')
    truyThu = fields.Char(string='Truy Thu')
    maDongHoCu = fields.Char(string='Mã Đồng Hồ Cũ')
    chiSoDauCu = fields.Char(string='Chỉ Số Đầu Cũ')
    chiSoCuoiCu = fields.Char(string='Chỉ Số Cuối Cũ')
    ngayThayDongHo = fields.Char(string='Ngày Thay Đồng Hồ')
    soHoaDon = fields.Char(string='Số Hóa Đơn')
    seriHoaDon = fields.Char(string='Sê-ri Hóa Đơn')
    ngayLapHoaDon = fields.Char(string='Ngày Lập Hóa Đơn')
    mucDich = fields.Char(string='Mục Đích')
    tenMucDich = fields.Char(string='Tên Mục Đích')
    maDoiTuongGia = fields.Char(string='Mã Đối Tượng Giá')
    tieuThu = fields.Char(string='Tiêu Thụ')
    thanhTien = fields.Char(string='Thành Tiền')
    phiVAT = fields.Char(string='Phí VAT')
    phiBVMT = fields.Char(string='Phí BVMT')
    phiDuyTriDauNoi = fields.Char(string='Phí Duy Trì Đầu Nối')
    tongTien = fields.Char(string='Tổng Tiền')
    ngayDauKy = fields.Char(string='Ngày Đầu Kỳ')
    ngayCuoiKy = fields.Char(string='Ngày Cuối Kỳ')
    ngayHoaDon = fields.Char(string='Ngày Hóa Đơn')
    daThanhToan = fields.Char(string='Đã Thanh Toán')
    nguoiThuTien = fields.Char(string='Người Thu Tiền')
    maKhuVuc = fields.Char(string='Mã Khu Vực')
    maSoThue = fields.Char(string='Mã Số Thuế')
    soNhanKhau = fields.Char(string='Số Nhân Khẩu')
    tongTienBangChu = fields.Char(string='Tổng Tiền Bằng Chữ')
    diaChiSuDungNuoc = fields.Char(string='Địa Chỉ Sử Dụng Nước')
    hinhThucThanhToan = fields.Char(string='Hình Thức Thanh Toán')
    seriDongHoCu = fields.Char(string='Sê-ri Đồng Hồ Cũ')
    maVach = fields.Char(string='Mã Vạch')
    maLoaiKhachHang = fields.Char(string='Mã Loại Khách Hàng')
    soHoDungChung = fields.Char(string='Số Hộ Dùng Chung')
    ngayThuTien = fields.Char(string='Ngày Thu Tiền')
    ngayCapNhatThuTien = fields.Char(string='Ngày Cập Nhật Thu Tiền')
    maVung = fields.Char(string='Mã Vùng')
    maDongHoCha = fields.Char(string='Mã Đồng Hồ Cha')
    soDienThoai = fields.Char(string='Số Điện Thoại')
    tenNhaMang = fields.Char(string='Tên Nhà Mạng')
    xDaiDien = fields.Char(string='X Đại Diện')
    yDaiDien = fields.Char(string='Y Đại Diện')
    ghiChu = fields.Char(string='Ghi Chú')