# -*- coding: utf-8 -*-
{
    'name': 'Sơn Hà quản lý xuất khẩu',
    'version': '1.0',
    'category': 'Uncategorized',
    'summary': 'Quản lý đơn hàng xuất khẩu',
    'website': 'https://hrm.sonha.com.vn/',
    'description': "Quản lý đơn hàng xuất khẩu",
    'depends': ['base', 'mail', 'hr', 'sonha_menu_access'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/cron_job.xml',
        'data/mail_template.xml',
        'views/exp_contract_views.xml',
        'views/exp_contract_state_views.xml',
        'views/exp_contract_state_log_views.xml',
        'views/exp_document_type_views.xml',
        'views/exp_production_order_views.xml',
        'views/exp_shipment_views.xml',
        'views/exp_customer_views.xml',
        'views/exp_state_transition_rule_views.xml',
        'views/exp_task_reminder_views.xml',
        'wizard/popup_contract_filter_list_views.xml',
        'wizard/popup_required_document_views.xml',
        'wizard/popup_export_document_views.xml',
        'wizard/popup_config_mail_template_views.xml',
        'wizard/popup_invoice_pkl_choose_views.xml',
        'wizard/popup_multi_invoice_pkl_views.xml',
        'views/exp_contract_api_views.xml',
        'views/exp_co_bh_reminder_views.xml',
        'views/exp_config_data_views.xml',
        'views/exp_export_document_views.xml',
        'views/exp_group_users_views.xml',
        'views/exp_distribute_group_user_views.xml',
        'views/exp_mail_config_views.xml',
        'views/exp_config_country_views.xml',
        'views/exp_config_term_views.xml',
        'views/exp_config_port_views.xml',
        'views/exp_config_bank_views.xml',
        'views/exp_config_currency_views.xml',
        'views/contract_button_filter_template.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sonha_ql_xuat_khau/static/src/js/contract_button_filter.js',
            'sonha_ql_xuat_khau/static/src/xml/contract_button_filter.xml',
            'sonha_ql_xuat_khau/static/src/js/m2m_user_widget.js',
            'sonha_ql_xuat_khau/static/src/xml/m2m_user_widget.xml',
            'sonha_ql_xuat_khau/static/src/css/style.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
