# -*- coding: utf-8 -*-
{
    'name': 'Báo cáo Sơn Hà',
    'version': '1.0',
    'category': 'Uncategorized',
    'summary': 'Báo cáo Sơn Hà',
    'website': 'https://',
    'description': "Báo cáo Sơn Hà",
    'depends': ['base', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/employee_report_views.xml',
        'views/config_template_views.xml',
        'views/master_data_report_views.xml',
        'views/employee_attendance_report_views.xml',
        'views/synthetic_work_report_views.xml',
        'views/sonha_word_report_views.xml',
        'views/leave_report_views.xml',
        'views/synthetic_leave_report_views.xml',
        'views/reward_report_views.xml',
        'views/discipline_report_views.xml',
        'views/dismissal_report_views.xml',
        'views/word_slip_report_views.xml',
        'views/dashboard_action.xml',
        'views/menu_report_views.xml',
        'wizard/popup_master_data_report_views.xml',
        'wizard/popup_employee_attendance_report_views.xml',
        'wizard/popup_synthetic_work_report_views.xml',
        'wizard/popup_employee_shift_report_views.xml',
        'wizard/popup_leave_report_views.xml',
        'wizard/popup_synthetic_leave_report_views.xml',
        'wizard/popup_sonha_employee_report_views.xml',
        'wizard/popup_sonha_contract_report_views.xml',
        'wizard/export_report_employee.xml',
        'wizard/popup_reward_report_views.xml',
        'wizard/popup_discipline_report_views.xml',
        'wizard/popup_dismissal_report_views.xml',
        'wizard/popup_word_slip_report_views.xml',
        'wizard/popup_overtime_report_views.xml',
        'wizard/export_report_reward_discipline.xml',
    ],

    'assets': {
        'web.assets_backend': [
            'sonha_report/static/src/components/employee_greet_dashboard.js',
            'sonha_report/static/src/components/employee_greet_dashboard.xml',
        ],
    },

    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
